# Generated by Django 5.2.4 on 2025-07-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
